#!/bin/bash
if [ $# -lt 1 ]; then
    echo Not enough arguments
    exit 1
fi

shopt -s nocasematch

for k in $*; do

    if [ ! -e $k ]; then
        echo 'Error in check_dependencies:' ${k}' does not exist.'
        continue
    fi

    if [ -d $k ]; then
        TO=$k/*
    else
        TO=$k
    fi

    for m in $TO; do
        FNAME=$m
        if [[ "${FNAME:(-3)}" != 'f90' ]]; then
           continue 
        fi
        S=`grep -F 'USE ' $FNAME`

        if [ "$S" == '' ]; then
            S=`grep -F 'use ' $FNAME`
        fi

        T=`for i in $S; do
            if [[ "$i" == 'omp_lib' ]]; then
                R=0
                continue
            fi
            if [[ $R == 1 ]]; then
                echo ${i%%,*}
                R=0
            fi
            if [[ "$i" == "use" ]]; then
                R=1
            fi
        done | sort`

        j=''
        U=`for i in $T
        do if [[ "$i" != "$j" ]]; then
            echo $i.o
            j=$i
        fi
        done`

        N=$FNAME
        N=${N:0:${#N}-4}
        echo ${N}'.o: '$U

    done

done
